---
- name: "Gather all IOS facts"
  hosts: routers
  gather_facts: False

  tasks:
    - name: "Gather all IOS facts"
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources:
          - l3_interfaces
          - hostname
          - interfaces
          - static_routes
          - l2_interfaces
      register: ios_facts
