---
- name: "PRE-TASK -- Setup initial network"
  ansible.builtin.import_playbook: initial-network.yml

- name: "TEST-CASE #3 -- Set incorrect next-hop parameter in R3 router"
  # Source: 10.0.1.2/24
  # Destination: 10.0.2.2/24
  gather_facts: False
  hosts: R3
  vars_files:
    - ../vars/test-case-3.yml
  
  tasks:
    - name: "Set static route"
      ansible.builtin.include_role:
        name: cisco-config-static_routes
      vars:
        routes: "{{ R3.routes }}"

# Steps to eliminate this error:
# 1. Get current config - check if routes exists considering if their interfaces are enabled or not!
# 2. Go through interfaces - enable all of them which has an IP address and not enabled
# 3. Check loops - if there is a loop, proceed to #4
# 4.