---
- name: "PRE-TASK -- Setup initial network"
  ansible.builtin.import_playbook: initial-network.yml

- name: "TEST-CASE #2 -- Turn off an interface in the route"
  # Source: 10.0.2.2/24
  # Destination: 10.0.1.2/24
  gather_facts: False
  hosts: R1
  vars_files:
    - ../vars/test-case-2.yml
  
  tasks:
    - name: "Change interface status on R1"
      ansible.builtin.include_role:
        name: cisco-config-interfaces
      vars:
        interfaces: "{{ R1.interfaces }}"
