---
- name: "PRE-TASK -- Setup initial network"
  ansible.builtin.import_playbook: initial-network.yml

- name: "TEST-CASE #2 -- Set incorrect next-hop parameter in R3 router"
  gather_facts: False
  hosts: R3
  vars_files:
    - ../vars/test-case-2.yml
  
  tasks:
    - name: "Set static route"
      ansible.builtin.include_role:
        name: cisco-config-static_routes
      vars:
        routes: "{{ R3.routes }}"
      