all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 10.10.20.101
        R2:
          ansible_host: 10.10.20.102
        R3:
          ansible_host: 10.10.20.103
        R4:
          ansible_host: 10.10.20.104
        R5:
          ansible_host: 10.10.20.105
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: cisco
        ansible_password: cisco
        ansible_become: yes 
        ansible_become_method: enable
        ansible_become_password: cisco
    desktops:
      hosts:
        PC1:
          ansible_host: 10.10.20.111
        PC2:
          ansible_host: 10.10.20.112
      vars:
        ansible_connection: ssh
        ansible_user: cisco
        ansible_password: cisco
