---
- name: "PRE-TASK -- Setup initial network"
  ansible.builtin.import_playbook: initial-network.yml

- name: "TEST-CASE #1 -- Remove a route from the path between PC1 and PC2"
  gather_facts: False
  hosts: R2
  vars_files:
    - ./vars/test-case-1.yml
  
  tasks:
    - name: "Set static route"
      ansible.builtin.include_role:
        name: cisco-config-static_routes
      vars:
        routes: "{{ R2.routes }}"
      